version: '3'

networks:
  sim:
    driver: bridge

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    container_name: etcd
    restart: on-failure
    privileged: true
    ports:
      - "2379:2379"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - ETCD_API=3
      - ETCD_CERT_FILE="/path/to/server.crt"
      - ETCD_KEY_FILE="/path/to/server.key"
      - ETCD_AUTH="simple"
      - ETCD_AUTH_USER="todolist"
      - ETCD_AUTH_PASSWORD="todolist"
    networks:
      - sim

  etcd-keeper:
    image: "evildecay/etcdkeeper:latest"
    container_name: etcd-keeper
    environment:
      - ETCD_HOSTS = http://etcd:2379
      - SW_STORAGE_ETCD_CLUSTER_NODES = etcd:2379
      - HOST = 127.0.0.1
      - HOSTNAME = etcd-keeper
    links:
      - etcd
    ports:
      - "8080:8080"
    networks:
      - sim

  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/var/docker/mq/rabbitmq/lib:/var/lib/rabbitmq
      - ~/var/docker/mq/rabbitmq/etc:/etc/rabbitmq
      - ~/var/docker/mq/rabbitmq/log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq-1
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - sim